CREATE DATABASE PD_311_DDL

ON 
(
	NAME = PD_311_DDL_DAT,
	FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PD_311_DDL.mdf',
	SIZE = 8 MB,
	MAXSIZE = 512 MB,
	FILEGROWTH = 8 MB
)
LOG ON
(
	NAME = PD_311_DDL_log,
	FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PD_311_DDL_log.ldf',
	SIZE = 8MB,
	MAXSIZE = 512MB,
	FILEGROWTH = 8MB
);